version: '3.8'

services:
  web:
    build: .
    command: ["/app/docker/app.sh"]
    container_name: horse_club_backend
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
    - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: horse_club_db
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    user: ${UID}:${GID}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .prod_env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
       - 5432:5432
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${SMTP_USER}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    command: >
      --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  worker1:
    build: .
    command: ["/app/docker/celery.sh", "worker"]
    environment:
      - API_REDIS_HOST=redis
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

#  worker2:
#    build: .
#    command: ["/app/docker/celery.sh", "worker"]
#    environment:
#      - API_REDIS_HOST=redis
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#      - db

  flower:
    build: .
    command: ["/app/docker/celery.sh", "flower"]
    volumes:
      - .:/app
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
    environment:
      - API_REDIS_HOST=redis
volumes:
  pgadmin: