"""add horse models fix 4

Revision ID: 0dd7c7dd3469
Revises: 49336d4bd973
Create Date: 2023-03-22 01:31:06.534049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd7c7dd3469'
down_revision = '49336d4bd973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
