"""Initial user add user add table_args

Revision ID: 12474f367fcd
Revises: 6d42c05d9f65
Create Date: 2023-03-15 21:05:02.198662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12474f367fcd'
down_revision = '6d42c05d9f65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
