"""add horse models fix 2

Revision ID: 13fb2c124cec
Revises: 88d1ae8f253d
Create Date: 2023-03-21 21:21:32.430222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fb2c124cec'
down_revision = '88d1ae8f253d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
