"""add method to horse

Revision ID: 32ada90c205c
Revises: 0dd7c7dd3469
Create Date: 2023-03-22 21:19:58.896229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ada90c205c'
down_revision = '0dd7c7dd3469'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
