"""add horse models fix 3

Revision ID: 49336d4bd973
Revises: 13fb2c124cec
Create Date: 2023-03-22 01:20:20.892067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49336d4bd973'
down_revision = '13fb2c124cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
