"""Initial user add user add userinfo model

Revision ID: 49c241b41076
Revises: 12474f367fcd
Create Date: 2023-03-15 21:36:42.331427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c241b41076'
down_revision = '12474f367fcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
