"""add caskade horse

Revision ID: 6cc5b4844e87
Revises: 32ada90c205c
Create Date: 2023-03-27 21:47:03.728122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc5b4844e87'
down_revision = '32ada90c205c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
