"""Initial user add user fix

Revision ID: 6d42c05d9f65
Revises: 82518e6479e1
Create Date: 2023-03-12 21:07:38.219421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d42c05d9f65'
down_revision = '82518e6479e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(), nullable=False))
    op.add_column('role', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'permissions')
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
