"""add horse models fix

Revision ID: 88d1ae8f253d
Revises: 6d890380bd15
Create Date: 2023-03-21 21:18:04.475268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d1ae8f253d'
down_revision = '6d890380bd15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
