"""add caskade horse 1

Revision ID: 8ac2bbf97f6e
Revises: 6cc5b4844e87
Create Date: 2023-03-27 21:54:05.841411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac2bbf97f6e'
down_revision = '6cc5b4844e87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
