"""add horse models and horsephoto

Revision ID: aca977c706e3
Revises: 49c241b41076
Create Date: 2023-03-21 20:30:05.985045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca977c706e3'
down_revision = '49c241b41076'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
