"""add caskade horse 2

Revision ID: fa8e0e11f57d
Revises: 8ac2bbf97f6e
Create Date: 2023-03-27 21:56:28.689424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8e0e11f57d'
down_revision = '8ac2bbf97f6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
